version: '3'

services:

  # flag-api-backend:
  #   container_name: flag-api
  #   restart: on-failure
  #   ports:
  #     - 5000:5000

  frontend:
    build:
      context: .
    container_name: simple-form-ui
    ports:
      - 8080:8080
    # depends_on:
    #   - flag-api-backend